set(REQUIRED_QT_VERSION "5.2.0")
find_package(Qt5 ${REQUIRED_QT_VERSION} NO_MODULE REQUIRED Core Widgets)
#TODO: test KPROPERTY_KF
find_package(KF5 5.7.0 REQUIRED Config CoreAddons WidgetsAddons GuiAddons)
find_package(KPropertyCore ${PROJECT_VERSION} REQUIRED)
find_package(KPropertyWidgets ${PROJECT_VERSION} REQUIRED)
set(LIB_INSTALL_DIR "lib")
include(KDECMakeSettings NO_POLICY_SCOPE)
include(KDECompilerSettings NO_POLICY_SCOPE)
if(POLICY CMP0063) # Honor visibility properties for all target types (since cmake 3.3)
    cmake_policy(SET CMP0063 NEW)
endif()
