# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/kwidgetsaddons': '@stable'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
